name: Trigger CodeBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  trigger-codebuild:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ASIA32WXPXTCA6AQEUSP
        aws configure set aws_secret_access_key zs85Jr4jC5nw299I50+TDpg1WY8rAIN/DqXTe3Jk
        aws configure set region us-east-1

    - name: Start CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1
      with: 
        project-name: GitHubActionWithcbATandT
