name: Trigger CodeBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trigger-codebuild:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Start CodeBuild
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        
        # Use the AWS SDK for JavaScript to start the CodeBuild build
        const AWS = require('aws-sdk');
        AWS.config.update({
          region: 'us-east-1',
          credentials: {
            accessKeyId: process.env.AWS_ACCESS_KEY_ID,
            secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
          },
        });
        
        const codebuild = new AWS.CodeBuild();
        codebuild.startBuild({
          projectName: 'GitHubActionWithcbATandT',
        }, (err, data) => {
          if (err) {
            console.error('Error starting CodeBuild build:', err);
          } else {
            console.log('CodeBuild build started:', data.build.id);
          }
        });
